(function () {
  const sentences = { ko: ['작은 습관이 매일의 큰 변화를 만듭니다.', '정확하게 입력하면 더 좋은 기록을 얻을 수 있습니다.', '새로운 것을 배우는 시간은 언제나 가치가 있습니다.'], en: ['Small habits create meaningful change every day.', 'Accuracy helps you achieve a better score.', 'Learning something new is always worth the time.'] };
  const language = document.getElementById('typingLanguage'), duration = document.getElementById('typingDuration'), prompt = document.getElementById('typingPrompt'), input = document.getElementById('typingInput'), time = document.getElementById('typingTime'), result = document.getElementById('typingResult');
  let target = '', remaining = 0, timer = null, last = null;
  function chooseSentence() { const list = sentences[language.value]; return list[Math.floor(Math.random() * list.length)]; }
  function start() { clearInterval(timer); target = chooseSentence(); remaining = Number(duration.value); prompt.textContent = target; input.value = ''; input.disabled = false; input.focus(); result.classList.add('hidden'); time.textContent = remaining; language.disabled = duration.disabled = true; timer = setInterval(() => { remaining--; time.textContent = remaining; if (remaining <= 0) finish(); }, 1000); }
  function finish() { clearInterval(timer); input.disabled = true; language.disabled = duration.disabled = false; const typed = input.value; const correct = Array.from(typed).reduce((count, char, index) => count + (char === target[index] ? 1 : 0), 0); const errors = Math.max(0, typed.length - correct); const accuracy = typed.length ? Math.round((correct / typed.length) * 100) : 0; const elapsed = Number(duration.value); const cpm = Math.round((correct / elapsed) * 60); const wpm = Math.round((correct / 5 / elapsed) * 60); const speed = language.value === 'en' ? wpm : cpm; const unit = language.value === 'en' ? 'WPM' : 'CPM'; last = { speed, unit, accuracy, errors }; const key = 'typingBest_' + language.value + '_' + duration.value; const best = Number(localStorage.getItem(key)) || 0; const newBest = speed > best; if (newBest) localStorage.setItem(key, String(speed)); result.innerHTML = '<strong>타자 속도</strong><b>' + speed + ' ' + unit + '</b><p>정확도: ' + accuracy + '% · 오타: ' + errors + (newBest ? ' · 🏆 최고 기록 갱신!' : '') + '</p>'; result.classList.remove('hidden'); }
  document.getElementById('typingStart').addEventListener('click', start); document.getElementById('typingCopy').addEventListener('click', () => copyGameLink(window.location.href, { container: result })); document.getElementById('typingShare').addEventListener('click', () => { if (last) shareGameResult({ title: document.title, text: '⌨️ 타자 속도 테스트 결과\n\n속도: ' + last.speed + ' ' + last.unit + '\n정확도: ' + last.accuracy + '%', container: result }); }); prompt.textContent = '시작 버튼을 누르면 문장이 표시됩니다.';

if (typeof renderRelatedByCategory === 'function') {
  renderRelatedByCategory('relatedList', 'games', 'typing', 5);
}
})();