(function () {
  const boardEl = document.getElementById('sudokuBoard');
  const numbersEl = document.getElementById('sudokuNumbers');
  const difficultyEl = document.getElementById('sudokuDifficulty');
  const timeEl = document.getElementById('sudokuTime');
  const mistakesEl = document.getElementById('sudokuMistakes');
  const resultEl = document.getElementById('sudokuResult');
  let puzzle = [], solution = [], givens = [], selected = -1, mistakes = 0, seconds = 0, interval = null, complete = false;
  const base = [[1,2,3,4,5,6,7,8,9],[4,5,6,7,8,9,1,2,3],[7,8,9,1,2,3,4,5,6],[2,3,4,5,6,7,8,9,1],[5,6,7,8,9,1,2,3,4],[8,9,1,2,3,4,5,6,7],[3,4,5,6,7,8,9,1,2],[6,7,8,9,1,2,3,4,5],[9,1,2,3,4,5,6,7,8]];
  function shuffle(items) { return items.slice().sort(() => Math.random() - .5); }
  function generateSolution() { const digits = shuffle([1,2,3,4,5,6,7,8,9]); const rows = shuffle([0,1,2]).flatMap(group => shuffle([0,1,2]).map(row => group * 3 + row)); const cols = shuffle([0,1,2]).flatMap(group => shuffle([0,1,2]).map(col => group * 3 + col)); return rows.map(row => cols.map(col => digits[base[row][col] - 1])); }
  function formatTime(value) { return String(Math.floor(value / 60)).padStart(2, '0') + ':' + String(value % 60).padStart(2, '0'); }
  function render() { boardEl.innerHTML = ''; puzzle.flat().forEach((value, index) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'sudoku-cell'; if (givens.flat()[index]) button.classList.add('given'); if (value && value !== solution.flat()[index]) button.classList.add('wrong'); const same = selected >= 0 && value && value === puzzle[Math.floor(selected / 9)][selected % 9]; if (index === selected) button.classList.add('selected'); if (same) button.classList.add('match'); button.textContent = value || ''; button.setAttribute('aria-label', 'Cell ' + (index + 1)); button.addEventListener('click', () => { selected = index; render(); }); boardEl.appendChild(button); }); }
  function newGame() { clearInterval(interval); solution = generateSolution(); puzzle = solution.map(row => row.slice()); const removed = { easy: 36, medium: 46, hard: 54 }[difficultyEl.value]; shuffle(Array.from({ length: 81 }, (_, i) => i)).slice(0, removed).forEach(index => { puzzle[Math.floor(index / 9)][index % 9] = 0; }); givens = puzzle.map(row => row.map(Boolean)); selected = -1; mistakes = 0; seconds = 0; complete = false; mistakesEl.textContent = '0'; timeEl.textContent = '00:00'; resultEl.classList.add('hidden'); render(); interval = setInterval(() => { seconds++; timeEl.textContent = formatTime(seconds); }, 1000); }
  function enter(value) { if (complete || selected < 0) return; const row = Math.floor(selected / 9), col = selected % 9; if (givens[row][col]) return; if (value === 0) { puzzle[row][col] = 0; render(); return; } puzzle[row][col] = value; if (value !== solution[row][col]) { mistakes++; mistakesEl.textContent = mistakes; } if (puzzle.flat().every((item, index) => item === solution.flat()[index])) finish(); render(); }
  function finish() { complete = true; clearInterval(interval); const key = 'sudokuBest_' + difficultyEl.value; const best = Number(localStorage.getItem(key)) || 0; const newBest = !best || seconds < best; if (newBest) localStorage.setItem(key, String(seconds)); resultEl.innerHTML = '<strong>축하합니다!</strong><b>' + formatTime(seconds) + '</b><p>' + difficultyEl.options[difficultyEl.selectedIndex].text + (newBest ? ' · 🏆 최고 기록 갱신!' : '') + '</p>'; resultEl.classList.remove('hidden'); }
  numbersEl.innerHTML = [1,2,3,4,5,6,7,8,9].map(number => '<button type="button" data-number="' + number + '">' + number + '</button>').join(''); numbersEl.querySelectorAll('button').forEach(button => button.addEventListener('click', () => enter(Number(button.dataset.number))));
  document.addEventListener('keydown', event => { if (/^[1-9]$/.test(event.key)) enter(Number(event.key)); if (event.key === 'Backspace' || event.key === 'Delete') enter(0); });
  document.getElementById('sudokuNew').addEventListener('click', newGame); document.getElementById('sudokuCheck').addEventListener('click', () => { if (!complete) resultEl.innerHTML = '<p>실수: ' + mistakes + ' · 빈 칸을 모두 채워 보세요.</p>', resultEl.classList.remove('hidden'); }); document.getElementById('sudokuCopy').addEventListener('click', () => copyGameLink(window.location.href, { container: resultEl })); document.getElementById('sudokuShare').addEventListener('click', () => { if (complete) shareGameResult({ title: document.title, text: '🧩 스도쿠 ' + difficultyEl.options[difficultyEl.selectedIndex].text + ' 완료 시간: ' + formatTime(seconds), container: resultEl }); }); newGame();
})();